### PR TITLE
Add hybrd interface and example.

### PR DESCRIPTION
**Pull request by zoziha**
- [x] Add `hybrd` interface and example.
- [x] Improve `hybrd1` interface and example, mainly the comment part.
- [x] Add `example_hybrd` to `fpm.yml` (CI tasks).

### CODE REVIEW

**Comment by certik** [comment]
Thanks! Can you please also add it here: https://github.com/certik/minpack/blob/0366240deacf6602613a8bb807890805697cd5ce/.github/workflows/fpm.yml#L55 to ensure it runs at the CI?

**Comment by zoziha** [comment]
Okay, the addition of `fpm.yml` has been completed now.

**Review by certik — APPROVED** [review]
Perfect, thanks!

**Comment by certik** [comment]
@zoziha I added you as a member of this repository. So you should be able to merge PRs yourself now after they are reviewed. Go ahead and merge this one.

**Comment by zoziha** [comment]
Thanks! @certik

**Pull request merged**
